services:
  postgres:
    image: postgres:17
    container_name: restaurant_postgres
    environment:
      POSTGRES_DB: restaurant_hunt
      POSTGRES_USER: restaurant_hunt
      POSTGRES_PASSWORD: password1234
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: